---
# Nginx 설치 및 서비스 실행
- name: Install and start Nginx on target server
  hosts: all                  # 인벤토리 전체 → CI에선 단일 IP만 적용됨
  become: yes                 # root 권한 사용
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes     # 패키지 목록 갱신

    - name: Upgrade packages
      apt:
        upgrade: yes          # 전체 패키지 업그레이드

    - name: Install Nginx
      apt:
        name: nginx
        state: present        # 설치되어 있지 않으면 설치

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started        # 서비스 실행
        enabled: yes          # 부팅 시 자동 시작
